openapi: 3.0.0
info:
  title: Sample Node.js App
  description: A test app for demonstrating CI, monitoring, and security
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /my-app:
    get:
      summary: Root path
      responses:
        '200':
          description: Returns Hello, World!

  /about:
    get:
      summary: About page
      responses:
        '200':
          description: About information

  /ready:
    get:
      summary: Readiness probe
      responses:
        '200':
          description: App is ready

  /live:
    get:
      summary: Liveness probe
      responses:
        '200':
          description: App is alive

  /classified:
    get:
      summary: Secret path
      responses:
        '200':
          description: You should not be here!

  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200':
          description: App metrics
