name: Full CI and Docker Publish

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  nodejs:
    uses: ./.github/workflows/node-ci.yaml

  sast:
    uses: ./.github/workflows/sast.yaml

  container_scan:
    uses: ./.github/workflows/container-scan.yaml

  docker_publish:
    needs: [nodejs, sast, container_scan]
    if: ${{ success() }}
    uses: ./.github/workflows/container-build-publish.yaml
    secrets: inherit
