name: Container Image Scan

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  grype:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Grype Scan
    runs-on: ubuntu-latest

    steps:
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@v6
        id: scan
        with:
          image: "docker.io/pashok2398/paveld-rads:${{ github.event.workflow_run.head_commit.message }}"
          fail-build: true
          severity-cutoff: high
          only-fixed: true

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
