name: DAST

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:


jobs:
  Trigger_EthicalCheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Run EthicalCheck
        uses: apisec-inc/ethicalcheck-action@005fac321dd843682b1af6b72f30caaf9952c641
        with:
          oas-url: https://paveld-rads.druyan.net/api-docs
          email: "pavel@druyan.net"
          sarif-result-file: "ethicalcheck-results.sarif"

      - name: Check SARIF file
        run: |
          echo "Checking ethicalcheck-results.sarif..."
          ls -lh ethicalcheck-results.sarif || echo "File not found"
          cat ethicalcheck-results.sarif || echo "File is empty or invalid"

      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ethicalcheck-results.sarif

